# Generated by Django 3.1.2 on 2023-08-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0002_auto_20230829_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='test_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='test_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
