# Generated by Django 3.1.2 on 2023-08-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0003_auto_20230829_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='test_price',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='test_quantity',
        ),
        migrations.AddField(
            model_name='test',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
